set -euo pipefail
root=$1
mounts=$(findmnt --json --real --submounts --mountpoint "$root" -o TARGET,SOURCE,FSTYPE,OPTIONS,UUID)
jq -e '.filesystems | length > 0' <<< "$mounts" >/dev/null
escape_field() {
  local field=$1
  field=${field//\\/\\134}
  field=${field// /\\040}
  field=${field//$'\t'/\\011}
  field=${field//$'\n'/\\012}
  printf '%s' "$field"
}
printf '# Generated by runix-install from mounted filesystems\n'
while IFS= read -r entry; do
  target=$(jq -r .target <<< "$entry")
  mount_point=${target#"$root"}
  [ -n "$mount_point" ] || mount_point=/
  case "$mount_point" in /dev|/dev/*|/proc|/proc/*|/sys|/sys/*|/run|/run/*) continue ;; esac
  source=$(jq -r .source <<< "$entry")
  type=$(jq -r .fstype <<< "$entry")
  options=$(jq -r .options <<< "$entry")
  uuid=$(jq -r '.uuid // ""' <<< "$entry")
  # ZFS imports datasets by name, never by the block device UUID.
  if [ "$type" != zfs ] && [ -n "$uuid" ]; then source="UUID=$uuid"; fi
  pass=0
  case "$type" in ext2|ext3|ext4) pass=2; [ "$mount_point" != / ] || pass=1 ;; esac
  printf '%s %s %s %s 0 %s\n' "$(escape_field "$source")" "$(escape_field "$mount_point")" \
    "$(escape_field "$type")" "$(escape_field "$options")" "$pass"
done < <(jq -c '.. | objects | select(has("target"))' <<< "$mounts")
